apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  labels:
    app: app-backend
  namespace: azureregistery-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: azureregistery101.azurecr.io/image-workflow-1687293063347-img:latest
          ports:
            - containerPort: 3000